sudo: required
dist: stable
language: cpp

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - libboost1.67-dev

matrix:
  include:

  #
  # release-all (gcc)
  #
  - os: linux
    compiler: gcc
    addons:
      apt:
        packages:
          - build-essential 
          - cmake 
          - pkg-config 
          - libssl-dev 
          - libzmq3-dev 
          - libunbound-dev 
          - libsodium-dev 
          - libminiupnpc-dev 
          - libunwind8-dev 
          - liblzma-dev 
          - libreadline6-dev 
          - libldns-dev 
          - libexpat1-dev 
          - doxygen 
          - graphviz 
          - libpcsclite-dev 
          - libpgm-dev
      sources:
        - ubuntu-toolchain-r-test
    before_install:
      - sudo add-apt-repository -y ppa:mhier/libboost-latest
      - sudo apt-get update
    install:
      - sudo apt-get -y install libboost1.67-dev
    script:
      - make -j2

  #
  # release-all (clang)
  #
  - os: linux
    compiler: clang
    addons:
      apt:
        packages:
          - build-essential
          - cmake
          - pkg-config
          - libssl-dev
          - libzmq3-dev
          - libunbound-dev
          - libsodium-dev
          - libminiupnpc-dev
          - libunwind8-dev
          - liblzma-dev
          - libreadline6-dev
          - libldns-dev
          - libexpat1-dev
          - doxygen
          - graphviz
          - libpcsclite-dev
          - libpgm-dev
      sources:
        - ubuntu-toolchain-r-test
    before_install:
      - sudo add-apt-repository -y ppa:mhier/libboost-latest
      - sudo apt-get update
    install:
      - sudo apt-get -y install libboost1.67-dev
    script:
      - make -j2
